services:
  client:
    container_name: lap2_client
    build: ./client
    image: lap2_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  server:
    container_name: lap2_server
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=pg-admin
      - PGHOST=db
      - PGPASSWORD=pg-pass
      - PGDATABASE=blogs
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm start"

  db:
    container_name: lap2_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=blogs
      - POSTGRES_USER=pg-admin
      - POSTGRES_PASSWORD=pg-pass
volumes:
  dbdata:
networks: 
  default:
    name: lap2
