services:
  client:
    container_name: Lap2_client
    build: ./client
    image: lap2_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
